### ISSUE TITLE
Tutorial videos are marked as private

### ISSUE THREAD

**Issue by ronanpaixao** [los-cocos/cocos#256]
Tutorial videos featured on http://python.cocos2d.org/doc.html cannot be viewed. When one tries to play them, the message *"This video is private."* is shown.

**Comment by crutchcorn** [comment]
^^^

**Comment by nejdetckenobi** [comment]
+1.
Why are they private? And where is the #1 video?

**Comment by 1win1** [comment]
+1. It took a very long time and there was no response. No one wants renew the tutorial?

**Comment by songproducer** [comment]
+1 would like to see the tutorial videos but they're set to private!

**Comment by ccanepa** [comment]
as for now I see them online, and dangillet also sees them online.
If no one complains in a few days I will close the issue as solved

**Comment by nejdetckenobi** [comment]
I am complaining so you can't close the issue! Haha! Where is the first part? Do you have the #1 part?

**Comment by ccanepa** [comment]
@nejdetckenobi  :-) oh.. umh... I wiil look if it can be found. You are seeing all the others ?

**Comment by nejdetckenobi** [comment]
Other parts are fine! Thanks!

**Comment by ccanepa** [comment]
looks as if the #1 is the one linked in the start page ( http://python.cocos2d.org/index.html ), which links to https://www.youtube.com/watch?v=mrhfaoMvpps ( first frames say it is cocos #1, similar to the other videos )

Guess it wasn't listed in the docs / tutorials section because it is not a tutorial but a demo on effects.

**Comment by nejdetckenobi** [comment]
Ok now I can not complain.
