### ISSUE TITLE
Error when loading TMX map files

### ISSUE THREAD

**Issue by mdgilene** [los-cocos/cocos#278]
I am getting the following error when running the following code and when trying to open my map using the cocos map editor (tools/editor.py). It seems that "tile" is being referenced in the load_tmx function before it is being declared. Hopefully I'm not making a simple mistake but I do think this is a bug with the library and not my code.

```
Traceback (most recent call last):
  File "C:/Users/Matt/PycharmProjects/Cocos2D-Game/main.py", line 33, in <module>
    main()
  File "C:/Users/Matt/PycharmProjects/Cocos2D-Game/main.py", line 12, in main
    test_layer = cocos.tiles.load('./res/tilemap.tmx')['map0']
  File "C:\Python27\lib\site-packages\cocos2d-0.6.4-py2.7.egg\cocos\tiles.py", line 218, in load
    obj = load_tmx(filename)
  File "C:\Python27\lib\site-packages\cocos2d-0.6.4-py2.7.egg\cocos\tiles.py", line 393, in load_tmx
    cells[i][j] = cell_cls(i, j, tile_width, tile_height, {}, tile)
UnboundLocalError: local variable 'tile' referenced before assignment
```

```
import pyglet
from pyglet.window import key
import cocos
from cocos import actions, layer
from cocos.director import director


def main():
    global keyboard, scroller

    director.init(width=800, height=600, autoscale=False, resizable=True)

    scroller = layer.ScrollingManager()
    test_layer = cocos.tiles.load('./res/tilemap.tmx')['map0']
    scroller.add(test_layer)

    main_scene = cocos.scene.Scene(scroller)

    keyboard = key.KeyStateHandler()
    director.window.push_handlers(keyboard)

    def on_key_press(key, modifier):
        if key == pyglet.window.key.Z:
            if scroller.scale == .75:
                scroller.do(actions.ScaleTo(1, 2))
            else:
                scroller.do(actions.ScaleTo(.75, 2))
        elif key == pyglet.window.key.D:
            test_layer.set_debug(True)
    director.window.push_handlers(on_key_press)

    director.run(main_scene)

if __name__ == '__main__':
    main()
```

**Comment by ccanepa** [comment]
The for block that starts at line  382 found a gid (integer identifier used in layers to name tiles) that is not declared in any tileset.

Could be a malformed .tmx or a parsing error in cocos.

Malformed can be by a text-edit in the .tmx gone bad, or a combo of opers inside Tiled Editor that sets an inconsistent state, maybe replacing a tileset (?)

To get some cue about what area to look, the loop can be modified to print the position (in Tiled cells coords, ie from top left, like (untested):

```python
        for n, gid in enumerate(data):
            if gid < 1:
                tile = None
            else:
                # UGH
                tile_not_found = True
                for ts in tilesets:
                    if gid in ts:
                        tile = ts[gid]
                        tile_not_found = False
                        break
            i = n % width
            j = height - (n // width + 1)
            tiled_j = height - j - 1
            if tile_not_found:
                print("tile not found, gid=%d, Tiled position (cells from top left): %s" % (gid, (i, tiled_j)))
                tile = None
            cells[i][j] = cell_cls(i, j, tile_width, tile_height, {}, tile)
```

If you have more than one layer, print also layer.attrib['name'] after and outside the loop to know what layer.

Hopefully looking at that area into Tiled Editor will show what the problem is.

If you want, you can upload the .tmx and tileset images somewhere (dropbox, etc) so I can see what the problem is. [tileset images don't need to be the real ones, it can be solid color images with **same** dimensions as the originals]

**Comment by mdgilene** [comment]
Hmm, seems to have been a corrupted tmx file. Not sure how it got corrupted but I rebuilt some simple tile maps and it seems to be loading correctly now.
