### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by flylzj** [los-cocos/cocos#313]
I install cocos2d, and when i import cocos, EOFError happeded
![-78515e8d3fd6b357](https://user-images.githubusercontent.com/26559515/43132621-f9650856-8f6e-11e8-9663-07ce42c9a21b.png)

**Comment by ccanepa** [comment]
Looks like a pyglet problem related to future.

What happens if, in the same conditions (same current working dir, same python interpreter,...) in the python console

´´´´
import os
import pyglet
pyglet.resource.path.append(
    os.path.join(os.path.dirname(os.path.realpath(__file__)), "resources")
    )
pyglet.resource.reindex()
´´´
Be sure to use the same CWD as in your previous test, 'future' sometimes import unexpected things in the CWD

**Comment by flylzj** [comment]
Thank you, it just suddenly work but i don't know why : )
