### ISSUE TITLE
How to install Cocos2d?

### ISSUE THREAD

**Issue by ruichen0** [los-cocos/cocos#349]
When I try to install Cocos2d,there is a prompt of error like this:
"
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error                 
                                                      
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
"
How to solve it?

**Comment by dangillet** [comment]
Hi!

Sorry you encountered this issue. The problem is that we don't have - yet - a `pyproject.toml` file which would indicate that you need `setuptools` in order to run `setup.py`.

The quick fix for you right now is to create a virtual environment and install setuptools and wheel before installing cocos2d.

```bash
$ pip install setuptools wheel
$ pip install cocos2d
```
